app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, SelectField,
					 FieldList, FormField,
					 SelectMultipleField)
from wtforms import DateField as OGDateField

from wtforms.fields import Field
from wtforms.validators import (DataRequired, Length,
	InputRequired, ValidationError, Email, Optional)
from wtforms.widgets import TextInput

datetimeformat='%Y-%m-%dT%H:%M' # To get form.field.data to work. Does not work with the default (bug)

# class TagListField(Field):
# 	widget = TextInput()

# 	def _value(self):
# 		if self.data:
# 			return u', '.join(self.data)
# 		else:
# 			return u''

# 	def process_formdata(self, valuelist):
# 		if valuelist:
# 			self.data = [x.strip() for x in valuelist[0].split(',')]
# 		else:
# 			self.data = []

# class ConstraintForm(FlaskForm):
# 	""" The form for a single constraint """
# 	# base_nodes = FieldList(FormField(BaseNodeForm),min_entries=1,max_entries=10)
# 	# constant_nodes = FieldList(FormField(ConstantNodeForm),min_entries=1,max_entries=10)
# 	# operator_nodes = FieldList(FormField(OperatorNodeForm),min_entries=1,max_entries=10)
# 	# used_target_boxes = FieldList(FormField())
# 	# constraint_str = StringField('Type your constraint:',validators=[InputRequired()])


class SetupForm(FlaskForm):
	""" The top level form """

	regime = SelectField('Regime:', 
		choices=[('supervised','supervised'),('RL','RL')],
				 validators=[InputRequired()])

	sub_regime = SelectField('Sub-regime:', 
		choices=[('classification','classification'),('regression','regression')],
				 validators=[InputRequired()])

	sensitive_attributes = StringField('Sensitive attributes (comma separated):', 
				 validators=[],id='sensitive_attributes')
	# taglist = TagListField("Tag list here",render_kw={'disabled':''})
	# taglist = TagListField("Tag list here")
	# constraint_forms = FieldList(FormField(ConstraintForm),min_entries=1,max_entries=10)

	submit = SubmitField('Submit',id="submit_btn")


# class BaseNodeForm(FlaskForm):
# 	""" The form for a single base node """

	

app/main/routes.py
from flask import (render_template, request, redirect, abort, Blueprint,
				   session, url_for, flash,
				   jsonify,current_app,send_from_directory)
from werkzeug.utils import secure_filename
from .forms import SetupForm
from .utils import allowed_file
import numpy as np
import os

from seldonian.parse_tree.operators import measure_functions_dict
from seldonian.parse_tree.parse_tree import ParseTree
# from seldonian.io_utils import load_json

math_operators = ['+','-','*','/']
math_functions = ['min()','max()','abs()','exp()']

main = Blueprint('main',__name__)

@main.route("/",methods=["GET"]) 
def home(): 
	return render_template('home.html')

@main.route("/gui",methods=["GET","POST"]) 
def gui(): 
	setup_form = SetupForm()
	setup_form.sensitive_attributes.data = "M,F"
	if request.method == 'POST':
		print(request.form)

	return render_template('gui.html',setup_form=setup_form,
		measure_functions_dict=measure_functions_dict,
		math_operators=math_operators,
		math_functions=math_functions)

@main.route("/process_constraints",methods=["GET","POST"]) 
def process_constraints(): 
	print("Inside process_constraints()")
	# Validate constraint

	constraints = request.json['constraintsData']
	form_data = request.json['formData']
	# constraints = request.json['constraintsData']
	print("The constraint strings are: ")
	print(constraints)

	regime_dict = form_data[0]
	regime = regime_dict['value']
	if regime == 'supervised':
		sub_regime_dict = form_data[1]
		sub_regime = sub_regime_dict['value']
		sensitive_attributes_dict = form_data[2]
		sensitive_attributes = sensitive_attributes_dict['value']
		print(regime,sub_regime,sensitive_attributes)
	elif regime == 'RL':
		sub_regime = "all"
		sensitive_attributes = []
	# columns = ["M","F"]
	parse_trees = []
	for constraint_str in constraints:
		pt = ParseTree(delta=0.05,regime=regime,
			sub_regime=sub_regime,columns=sensitive_attributes)
		try:
			pt.create_from_ast(constraint_str)
		except Exception as e:
			print(e)
			return jsonify(success=0,
				error_msg=("Issue building the parse tree for constraint: "
						  f"{constraint_str}"))

	return jsonify(success=1)

@main.route("/test",methods=["GET","POST"]) 
def test(): 
	
	return render_template('test.html')

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet" />
		<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='main.css') }}">
		<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
		
		<script type="text/javascript" async
		  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
		</script>

		<title>Seldonian Interface GUI</title>
</head>
<body>
		<header class="site-header">
			<nav class="navbar navbar-expand-lg navbar-dark bg-steel static-top">
			  <div class="container">
			    <a class="navbar-brand">
			          <img src="{{url_for('static',filename='NN_thumb.png')}}" style="height:50px" alt="">
			        </a>
			    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			          <span class="navbar-toggler-icon"></span>
			        </button>
			    <div class="collapse navbar-collapse" id="navbarResponsive">
			      <ul class="navbar-nav ml-auto">
			        <li class="nav-item active">
			          <a class="nav-link" href="{{url_for('main.home')}}">Home
			                <span class="sr-only">(current)</span>
			              </a>
			        </li>
			        <li class="nav-item active">
			          <a class="nav-link" href="{{url_for('main.gui')}}">GUI
			                <span class="sr-only">(current)</span>
			              </a>
			        </li>
			      </ul>
			    </div>
			  </div>
			</nav>
		</header>

	<main role="main" class="container">
				  {% with messages = get_flashed_messages(with_categories=true) %}
					{% if messages %}
					  {% for category, message in messages %}
						<div class="alert alert-{{ category }}">
						  {{ message }}
						</div>
					  {% endfor %}
					{% endif %}
				  {% endwith %}
				{% block content %}{% endblock %}
	</main>
	


		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>